---
- name: Create S3 OpenShift registry user
  iam:
    iam_type: user
    name: "{{ s3_username }}"
    state: present
    access_key_state: create
  register: s3user
- name: Set fact
  set_fact: s3user_id="{{ s3user.user_meta.access_keys.0.access_key_id }}"
- name: Set fact
  set_fact: s3user_secret="{{ s3user.user_meta.access_keys.0.secret_access_key }}"
- name: Apply Full S3 privileges to s3 account
  iam_policy:
    iam_name: "{{ s3user.user_meta.access_keys.0.user_name }}"
    iam_type: "user"
    policy_name: S3FullAccess
    policy_json:
      Version: '2012-10-17'
      Statement:
          - Action: ['s3:*']
            Effect: Allow
            Resource: '*'
    state: present
