- hosts: localhost
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      # Group systems
      - instance-groups
- hosts: primary_master
  gather_facts: no
  become: yes
  vars_files:
      - vars/main.yaml
  roles:
      - openshift-demo
