---
- name: Create Role used by OpenShift
  iam:
    iam_type: role
    name: ose-ebs
    state: present
  register: ose-ebs
- name: Create policy used for Role
  iam_policy:
    iam_name: ose-ebs
    iam_type: "role"
    policy_name: ose-ebs
    policy_json:
      Version: '2012-10-17'
      Statement:
          - Action: ['ec2:Describe*']
            Effect: Allow
            Resource: '*'
          - Action: ['ec2:CreateVolume']
            Effect: Allow
            Resource: '*'
          - Action: ['ec2:AttachVolume']
            Effect: Allow
            Resource: '*'
          - Action: ['ec2:DetachVolume']
            Effect: Allow
            Resource: '*'
    state: present
