#!/bin/bash

# Source Variables
source ../vars &> /dev/null

#DELETE_KEYS() {
###
#
#
# DELETE KEY PAIRS
#
#
###

#aws ec2 delete-key-pair --key-name ${KEY_NAME}
#echo "deleting keys"
#}


DELETE_IAM_ROLES() {
###
#
#
# DELETE IAM ROLES
#
#
###

aws iam delete-user-policy --policy $EBS_POLICY_NAME
echo "deleted IAM roles"
}


DELETE_INSTANCES() {
###
#
#
# DELETE INSTANCES and EIP
#
#
###

BASTION=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters Name=instance-state-name,Values=running --filters Name=instance.group-name,Values=$BASTION_SEC_GROUP --output text)

DEL_EIP=$(aws ec2 describe-addresses --query 'Addresses[].AllocationId[]' --filters "Name=instance-id,Values=$BASTION" --output text)

MASTER0=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-master00.*" --output text)
MASTER1=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-master01.*" --output text)
MASTER2=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-master02.*" --output text)
NODE0=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-node00.*" --output text)
NODE1=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-node01.*" --output text)
APPNODE0=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-app-node00.*" --output text)
APPNODE1=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId]' --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=${UNIQ_VAR}-app-node01.*" --output text)

for INSTANCES in $BASTION $MASTER0 $MASTER1 $MASTER2 $NODE0 $NODE1 $APPNODE0 $APPNODE1; 
    do aws ec2 terminate-instances --instance-ids $INSTANCES
done
sleep 40

aws ec2 release-address --allocation-id $DEL_EIP
echo "deleted instances"
}


DELETE_LB() {
###
#
#
# DELETE LOAD BALANCERS
#
#
###

aws elb delete-load-balancer --load-balancer-name $MASTER_LB_NAME
aws elb delete-load-balancer --load-balancer-name $INTERNAL_MASTER_LB_NAME
aws elb delete-load-balancer --load-balancer-name $ROUTER_LB_NAME
echo "deleted load balancer"
}

DELETE_SEC_GRPS() {
###
#
#
# DELETE SECURITY GROUPS
#
#
###

sleep 45

VPC_ID=$(aws ec2 describe-vpcs --query Vpcs[].VpcId[] --filters Name=cidr,Values=$CIDR --output text)

NODE_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$NODES_SEC_GROUP" --output text)
ROUTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$ROUTER_ELB_SEC_GRP" --output text)
APP_NODES_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$APP_NODES_SEC_GROUP" --output text)
MASTER_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values=$MASTERS_SEC_GROUP --output text)
BASTION_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$BASTION_SEC_GROUP" --output text)
MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$MASTER_ELB_SEC_GRP" --output text)
INTERNAL_MASTER_ELB_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=group-name,Values="$INTERNAL_MASTER_ELB_SEC_GRP" --output text)
VPC_DEFAULT_SEC_GRP_ID=$(aws ec2 describe-security-groups --query SecurityGroups[].GroupId[] --filters Name=vpc-id,Values=$VPC_ID --output text)

for SECURITY_GROUPS in $NODE_SEC_GRP_ID $ROUTER_ELB_SEC_GRP_ID $REG_ELB_SEC_GRP_ID $APP_NODES_SEC_GRP_ID $MASTER_SEC_GRP_ID $BASTION_SEC_GRP_ID $INTERNAL_MASTER_ELB_SEC_GRP_ID $MASTER_ELB_SEC_GRP_ID; do
    aws ec2 delete-security-group --group-id $SECURITY_GROUPS
done
echo "deleted security groups"
}

DELETE_DNS() {
###
#
#
# DELETE DNS
#
#
###

# get infrastructure dns zone id
HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name --dns-name=$INFRA_DNS --output text | awk '/HOSTED/ { print $3 }')
# get reverse dns zone id
REV_HOSTED_ZONE=$(aws route53 list-hosted-zones-by-name --dns-name=$DNS_PTR --output text | awk '/30.10.in-addr.arpa./ { print $3 }' | grep hostedzone)

# Delete application records
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../app-nodes/app-node/node00-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../app-nodes/app-node/node01-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../app-nodes/app-node/node00-ptr-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../app-nodes/app-node/node01-ptr-record-terminate.json

# Delete bastion nodes
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../bastion/bastion/bastion-resource-record-terminate.json

# Delete master nodes
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../master/master/master00-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../master/master/master00-ptr-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../master/master/master01-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../master/master/master01-ptr-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../master/master/master02-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../master/master/master02-ptr-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../master/master/master-elb-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../master/master/internal-master-elb-a-record-terminate.json

# Delete infrastructure nodes
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../infra-nodes/node/node00-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../infra-nodes/node/node00-ptr-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../infra-nodes/node/node01-a-record-terminate.json
aws route53 change-resource-record-sets --hosted-zone-id $REV_HOSTED_ZONE --change-batch file://../infra-nodes/node/node01-ptr-record-terminate.json

# Delete router elb record
aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE --change-batch file://../router-elb/router-elb-a-record-terminate.json


# Delete hosted zones

aws route53 delete-hosted-zone --id $HOSTED_ZONE
aws route53 delete-hosted-zone --id $REV_HOSTED_ZONE
echo "deleted dns"
}

DELETE_VPC() {
###
#
#
# DELETE VPC
#
#
###
VPC_ID=$(aws ec2 describe-vpcs --query Vpcs[].VpcId[] --filters Name=cidr,Values=$CIDR --output text)

# Grab the subnet ID so we can assign tags to it.
SUBNET_ID_1=$(aws ec2 describe-subnets \
--query Subnets[].SubnetId[] \
--filters Name=cidr,Values=$SUBNET_CIDR_1 \
--output text)

SUBNET_ID_2=$(aws ec2 describe-subnets \
--query Subnets[].SubnetId[] \
--filters Name=cidr,Values=$SUBNET_CIDR_2 \
--output text)

SUBNET_ID_3=$(aws ec2 describe-subnets \
--query Subnets[].SubnetId[] \
--filters Name=cidr,Values=$SUBNET_CIDR_3 \
--output text)

aws ec2 delete-subnet --subnet-id $SUBNET_ID_1
aws ec2 delete-subnet --subnet-id $SUBNET_ID_2
aws ec2 delete-subnet --subnet-id $SUBNET_ID_3

ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
--query RouteTables[].RouteTableId \
--filters Name=route.destination-cidr-block,Values=$CIDR \
--output text)

ROUTE_TABLE=$(aws ec2 describe-route-tables --query 'RouteTables[].RouteTableId[]' --filters Name=vpc-id,Values=$VPC_ID --output text)

aws ec2 delete-route-table --route-table-id $ROUTE_TABLE

DEL_IG=$(aws ec2 describe-internet-gateways --query 'InternetGateways[]' --filters "Name=tag:Name,Values=$IG_TAG" --output text | grep igw)

aws ec2 detach-internet-gateway --internet-gateway-id $DEL_IG --vpc-id $VPC_ID
aws ec2 delete-internet-gateway --internet-gateway-id $DEL_IG

aws ec2 delete-vpc --vpc-id $VPC_ID
echo "deleted vpc"

}

CLEAN_IAM() {
POL_ARN=$(cat /home/rcook/git/ose-on-aws/awscli/iam/pol_arn)
aws iam remove-role-from-instance-profile --instance-profile-name $INSTANCE_PROFILE --role-name $IAM_ROLE_NAME 
aws iam delete-instance-profile --instance-profile-name $INSTANCE_PROFILE
aws iam detach-role-policy --role-name $IAM_ROLE_NAME --policy-arn $POL_ARN
aws iam delete-role --role-name $IAM_ROLE_NAME
aws iam delete-policy --policy-arn $POL_ARN
echo "deleted IAM roles"
}

# Call functions
DELETE_IAM_ROLES
CLEAN_IAM
#DELETE_KEYS
DELETE_INSTANCES
DELETE_LB
DELETE_SEC_GRPS
DELETE_SEC_GRPS
DELETE_SEC_GRPS
DELETE_SEC_GRPS
DELETE_DNS
DELETE_VPC
