---
- name: create ETCD security group
  ec2_group:
     region: "{{ region }}"
     name: ose_etcd_sg
     vpc_id: "{{ vpc }}"
     description: Secuity Group for ETCD
     rules:
       # allow kubelet communication
       - proto: tcp
         from_port: 2379
         to_port: 2379
         group_name: ose_master_sg
       - proto: tcp
         from_port: 2380
         to_port: 2380
         group_name: ose_master_sg
     rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
  register: ose_etcd_sg
- name: Tag security group with a name
  ec2_tag:
     resource: "{{ ose_etcd_sg.group_id }}"
     region: "{{ region }}"
     state: present
     tags:
       Name: ose_etcd_sg
